name: Docker Image CI

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the front-end Docker image
      run: | 
        docker build . --file Dockerfile -t ghcr.io/studentsagainstcovid19/corona-aid-frontend-dev:latest
        echo "Build completed"
        
        echo ${CR_PAT} | docker login ghcr.io -u ${GITHUB_REPOSITORY_OWNER} --password-stdin
        echo "Login successful"
        
        docker push ghcr.io/studentsagainstcovid19/corona-aid-frontend-dev:latest    
        echo "Push successful"
      env:
        CR_PAT: ${{ secrets.CR_PAT }}